spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/admin
      database: fitness_activity_db



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082