spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/fitness_recommendations?authSource=admin
      database: fitness_recommendations


server:
  port: 8083


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
