spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/fitness_activity_db?authSource=admin
      database: fitness_activity_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking